ALTER TABLE "Agent" ADD COLUMN "trustTier" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN "qualityScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN "confidence" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN "riskScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN "diversityRatio" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN "feedbackCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN "rawAvgScore" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN "txIndex" INTEGER;
ALTER TABLE "OrphanResponse" ADD COLUMN "runningDigest" BLOB;
